### ISSUE TITLE
Request not matching with any route

### ISSUE THREAD

**Issue by sam-rusty** [alexliesenfeld/httpmock#102]
I am trying to mock stripe api by following the docs, but looks like i am doing something wrong.
I have the following code:

```let stripe_server = httpmock::MockServer::start();
std::env::set_var("STRIPE_API_URL", stripe_server.url("/v1"));
stripe_server
        .mock(|when, then| {
            when.path("/payment_intents");
            then.status(200);
        });
```
and in my stripe service i am using the `STRIPE_API_URL` variable and the endpoint look like this `http://127.0.0.1:51914/v1/payment_intents`, which should matches with the mock server. but i am getting `{"message":"Request did not match any route or mock"}`
I tried adding method and header_exists to when but nothing work. 

What am i missing? 

Thanks!

**Comment by alexliesenfeld** [comment]
The `stripe_server.mock` gives you a mock object, which you can use to check method calls and get ideas about what might be going wrong in your code.

Here is an example: https://github.com/alexliesenfeld/httpmock/blob/60e68ed338230f4efe7f35f3378e2fca945a26a2/tests/examples/getting_started_tests.rs#L23

**Comment by sam-rusty** [comment]
That prints `No request has been received by the mock server.`

**Comment by alexliesenfeld** [comment]
Then your client has not sent any requests to the mock server. Make sure the stripe client actually sends the request to the mock server. 

Please be aware that the mock server address is not static by default, as the port gets automatically assigned by the operating system. You can get the address like this:

https://github.com/alexliesenfeld/httpmock/blob/60e68ed338230f4efe7f35f3378e2fca945a26a2/tests/examples/getting_started_tests.rs#L20

**Comment by sam-rusty** [comment]
if you look at my code above, i am getting the address from mock server and passing to env variable to use inside of my stripe service. i verified that it is sending the request using mock server address including the port . to fix, i just replaced the `httpmock` with `mockito` and it works without any changes to stripe service.

**Comment by alexliesenfeld** [comment]
It would be good to have a look at an example project that does not work. This example project does work: https://gist.github.com/alexliesenfeld/8b6591fd39e1b85b987f0acb0adade71

So if it simply does work for your code by replacing libraries, I would suggest double checking your client code or mock setup.
