### ISSUE TITLE
Vulnerability GHSA-q6cp-qfwq-4gcv in httpmock's dependency - h2

### ISSUE THREAD

**Issue by orcame** [alexliesenfeld/httpmock#105]
### Summary
The dependency h2(0.3.24) has vulnerability issue, check details from https://github.com/advisories/GHSA-q6cp-qfwq-4gcv

### Details
The dependency h2(0.3.24) has vulnerability issue, check details from https://github.com/advisories/GHSA-q6cp-qfwq-4gcv
Fixed in 0.4.4

The 'hyper' has new version. Need to update.

### Dependency Tree

├─┬ httpmock 0.7.0 - Cargo
│ └─┬ hyper 0.14.28 - Cargo
│   └── h2 0.3.24 - Cargo

**Comment by alexliesenfeld** [comment]
Thanks!

**Comment by alexliesenfeld** [comment]
Should be fixed starting with v0.8.0-alpha.1
