### ISSUE TITLE
Keep docker images on docker hub up-to-date

### ISSUE THREAD

**Issue by jordanbailes** [alexliesenfeld/httpmock#110]
The last release on docker hub was over a year ago. There has been releases since including v0.7.0 in January and a v0.8.0 alpha version in the last couple of days. It would be useful to get new images including the latest alpha version.

**Comment by alexliesenfeld** [comment]
Yes, absolutely. Just pushed it to Docker Hub. 

https://hub.docker.com/layers/alexliesenfeld/httpmock/0.8.0-alpha.1/images/sha256-805c728725ff2816858e67d5068f93d006cac5c04811342ac1063b14df63083d?context=repo

**Comment by jordanbailes** [comment]
Thanks @alexliesenfeld
