### ISSUE TITLE
Documentation wrong about order of Mock matching

### ISSUE THREAD

**Issue by mjp4** [alexliesenfeld/httpmock#116]
From https://httpmock.rs/miscellaneous/faq/

> **In which order are mocks evaluated?**
> When the httpmock server receives a request that matches multiple mocks, they are evaluated in reverse order of their definition. This means the most recently defined mock takes precedence and will be used.

This is not correct. As mentioned in https://github.com/alexliesenfeld/httpmock/issues/60#issuecomment-1006966092 they are matched in order of definition.

If they were indeed matched in reverse order of definition, then that would provide a solution to https://github.com/alexliesenfeld/httpmock/issues/94. I think it would be the more intuitive order, but it is not the current behaviour.

**Comment by alexliesenfeld** [comment]
Thank you @mjp4 , I‘ll fix that.

**Comment by alexliesenfeld** [comment]
Fixed now
