### ISSUE TITLE
Mock.expect_body and binary data

### ISSUE THREAD

**Issue by Ch00k** [alexliesenfeld/httpmock#12]
Is there any way I can use `Mock.expect_body` with binary data (e.g. when I send POST request for a file upload)?

**Comment by alexliesenfeld** [comment]
There is no direct support for file upload yet. If your tests are not in standalone mode you can try to use the generic matcher function like this: 

`
.expect_match(|req: MockServerRequest| {
    req.body.as_ref().unwrap().eq("test")
})
` 
Where test is the file content in string representation.

**Comment by Ch00k** [comment]
I also tried this, and it works:

```rust
let mock_server = MockServer::start();

Mock::new()
    .expect_method(Method::POST)
    .expect_path("/foo")
    .expect_body("bar")
    .create_on(&mock_server);

let client = reqwest::blocking::Client::new();
client
    .post(&mock_server.url("/foo"))
    .body("bar".as_bytes())
    .send()
    .unwrap();
```

**Comment by alexliesenfeld** [comment]
@Ch00k Is this still an issue?

**Comment by Ch00k** [comment]
No, sorry, I forgot to close it :)
