### ISSUE TITLE
FR: Support for tokio 1.0

### ISSUE THREAD

**Issue by UebelAndre** [alexliesenfeld/httpmock#25]
I've done very little investigation here so I don't know the scope of this request but it'd be nice to update the version of tokio used here to help shrink my build graph. Hopefully this is as easy as changing the number 😅

**Comment by gdesmott** [comment]
Looks like we first need a stable release of `actix` with tokio 1.0 support.

**Comment by alexliesenfeld** [comment]
I'm working on this in https://github.com/alexliesenfeld/httpmock/pull/27.

**Comment by alexliesenfeld** [comment]
There is a new release [0.5.3](https://github.com/alexliesenfeld/httpmock/releases/tag/v0.5.3) that updated all dependencies to the most recent version.
