### ISSUE TITLE
DELETE can have a body

### ISSUE THREAD

**Issue by ilari-makimattila** [alexliesenfeld/httpmock#30]
Hello,

Thanks for the library. It's helping me a lot!

At the moment I am working with an API that expects a body with a DELETE request. As far as I can tell a [DELETE request is allowed to have a body](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/DELETE), but since it's listed in the `NON_BODY_METHODS` [here](https://github.com/alexliesenfeld/httpmock/blob/bb234645f6da3f4cbfcedf45881172f537e7a053/src/server/web/handlers.rs#L19) I can't use the fluent API to define the mock. Could delete be removed from that list?

This is not urgent because I can do a workaround with custom request matcher.

**Comment by alexliesenfeld** [comment]
Has been fixed with [V0.5.5](https://crates.io/crates/httpmock/0.5.5)

**Comment by alexliesenfeld** [comment]
Has been fixed with [V0.5.5](https://crates.io/crates/httpmock/0.5.5)
