### ISSUE TITLE
Asserting the absence of body, headers, etc

### ISSUE THREAD

**Issue by ducaale** [alexliesenfeld/httpmock#44]
I would like to assert that my HTTP request body is empty or that a certain header doesn't exist. Is this something that `httpmock` supports at the moment?

Currently, I can see there the following functions exist:
* `header_exists()`
* `query_params_exists()`
* `cookie_exists()`

It would be nice if an opposite version of them existed plus one for checking if the body is empty.

**Comment by ducaale** [comment]
Actually, there is `matches()` function that is flexible enough for my current needs
```rust
let server = MockServer::start();
let mock = server.mock(|when, then| {
    when.matches(|req: &HttpMockRequest| {
        !req.headers
            .as_ref()
            .map(|headers| headers.iter().any(|(key, _)| key == "authorization"))
            .unwrap_or(false)
    });
    then.body("final destination");
});
```

**Comment by alexliesenfeld** [comment]
There is no direct functionality that checks for the absence of attributes at the moment. It could be a valuable addition in the future though. Thanks! 

You can indeed use `matches()` for cases where built-in matcher functions are not sufficient. Just want to note that it cannot be used in combination with a [standalone mock server](https://docs.rs/httpmock/0.5.8/httpmock/#standalone-mode), but I think this is not what you are after. Glad you found a solution!

**Comment by ducaale** [comment]
Thanks for confirming. I have been trying to add some of the methods I mentioned to `httpmock::When` via extension traits

```rust
trait WhenExt {
    fn header_not_exists(self, name: String) -> Self;
}

impl WhenExt for httpmock::When {
    fn header_not_exists(self, name: String) -> Self {
        self.matches(|req: &HttpMockRequest| {
            !req.headers
                .as_ref()
                .map(|headers| headers.iter().any(|(key, _)| key == &name))
                .unwrap_or(false)
        })
    }
}
```

Unfortunately, this didn't work because `matches` doesn't accept closures
```
error[E0308]: mismatched types
    --> tests/cli.rs:1767:22
     |
1767 |           self.matches(|req: &HttpMockRequest| {
     |  ______________________^
1768 | |             !req.headers
1769 | |                 .as_ref()
1770 | |                 .map(|headers| headers.iter().any(|(key, _)| key == &name))
1771 | |                 .unwrap_or(false)
1772 | |         })
     | |_________^ expected fn pointer, found closure
     |
     = note: expected fn pointer `for<'r> fn(&'r HttpMockRequest) -> bool`
                   found closure `[closure@tests/cli.rs:1767:22: 1772:10]`
```

Is it possible to update `matches` to allow that?

**Comment by alexliesenfeld** [comment]
This is a limitation currently that is planned to be changed in the upcoming release 0.6.0.

**Comment by akhramov** [comment]
Is it feasible to have a more generic FnMut closure instead of a fn pointer?

The inability to capture local variables is very limiting. I had to use thread_local variables to provide state for the matcher. FWIW my use-case is intermittent requests / retry-behaviour
