### ISSUE TITLE
Add features to reduce dependencies

### ISSUE THREAD

**Issue by ufoscout** [alexliesenfeld/httpmock#46]
With my team we are evaluating `httpmock`; it really looks like a great project.
Anyway, our test compile-time increased substantially due to its number of dependencies.
Would it maybe be possible to reduce the dependencies using cargo features? For example, I guess `isahc` and some other "client-side" libraries are used only with a remote server; could they be made optional and enabled with a `remote` feature?

**Comment by alexliesenfeld** [comment]
Thanks for creating this issue! By looking at the [dependency tree](https://doc.rust-lang.org/cargo/commands/cargo-tree.html), I think it should be possible to reduce the number of dependencies that are required for regular usage (i.e., non-standalone mode) by about 30%. Most dependencies seem to be added by `isahc` and `async-std` (coming in though `async-object-pool`). I'll look into it.

**Comment by ducaale** [comment]
Making isahc optional would also let users remove OpenSSL from their dependency tree so their tests can work in rust-cross.

**Comment by kisik21** [comment]
Could isahc be potentially replaced by hyper's client capabilities, seeming as the code, at least in the ping case, is async? (see [src/api/adapter/mod.rs#L84-L108](https://github.com/alexliesenfeld/httpmock/blob/339945c54ceb134e266d293fa585ca17d92edcc7/src/api/adapter/mod.rs#L84-L108))
