### ISSUE TITLE
When / Then are now private in 0.6.0

### ISSUE THREAD

**Issue by jszwedko** [alexliesenfeld/httpmock#47]
Hi all,

It seems like in 0.6.0 `When` and `Then` were made private. We had previously used these types when defining our test cases: https://github.com/timberio/vector/blob/f85d2fbe70b1f40d1e3275b6173cda15ace80696/src/kubernetes/api_watcher.rs#L234-L257

Is it possible to re-expose these types?

Thank you!

**Comment by alexliesenfeld** [comment]
Hi and thanks for creating this issue! You are correct, it seems both types were unexported during recent refactorings. I created a fix release for this ([0.6.2](https://crates.io/crates/httpmock/0.6.2)). @jszwedko Could you please verify that it fixes your issue?

**Comment by jszwedko** [comment]
Awesome, thanks for the quick fix @alexliesenfeld ! I can verify 0.6.2 works for us.
