### ISSUE TITLE
Share variables between requests and responses

### ISSUE THREAD

**Issue by sr-gi** [alexliesenfeld/httpmock#49]
I've noticed something missing that would be, IMHO, pretty useful for testing external clients agains mocked servers.

That's sharing variables between requests and responses. For instance, let's say we have a client posting some JSON data to a server, and the server may reply based on that data. The `when` clause should be able to expose the request data so the `then` clase can read it and act accordingly.

**Comment by alexliesenfeld** [comment]
Thanks for creating this issue. This is a great idea. I’ll queue this in my LOP. I’d also be happy to accept a PR.
