### ISSUE TITLE
Is it possible to start multiple mock servers on different ports?

### ISSUE THREAD

**Issue by jeremyandrews** [alexliesenfeld/httpmock#5]
I'm testing redirects, and would like to test redirecting between servers. Is it possible to start multiple mock servers on different ports?

**Comment by alexliesenfeld** [comment]
At the moment this feature is not direclty provided by httpmock. Until now there was no use case for having multiple servers running in one test. I will consider adding such a feature in future though. In the meantime you can start a second server manually. To start a second server manually, say on port 3000, something like this could work:

```rust
lazy_static! {
    static ref SECOND_SERVER: std::sync::Mutex<std::thread::JoinHandle<()>> = {
        return std::sync::Mutex::new( thread::spawn(move || {
                start_server(HttpMockConfig {
                    expose: false,
                    port: 3000,
                    workers: 1
                });
            }));
    };
}

...
#[test]
#[with_mock_server]
fn my_test() {
    SECOND_SERVER.lock();
   ...
}
```

**Comment by jeremyandrews** [comment]
Thanks!

Is there a way to then create mock endpoints with this second server (and the default server at the same time)? I've not yet figured out how this would work.

**Comment by alexliesenfeld** [comment]
Unfortunately not. This is why I have edited my previous comment. I realized that too late. Sorry for the confusion. I will add this feature to my todo list though.

**Comment by alexliesenfeld** [comment]
This feature should be covered by #7.

**Comment by jeremyandrews** [comment]
Just following up to let you know this worked perfectly for my project: https://github.com/tag1consulting/goose/pull/112 -- thanks!

**Comment by alexliesenfeld** [comment]
Thanks for the good feedback! Glad it worked for you!
