### ISSUE TITLE
Move away from difference as it's unmaintained? [RUSTSEC-2020-0095]

### ISSUE THREAD

**Issue by jacobsvante** [alexliesenfeld/httpmock#50]
See https://rustsec.org/advisories/RUSTSEC-2020-0095

**Comment by alexliesenfeld** [comment]
Thanks for reporting. I do not see any criticality in replacing difference.rs at this time. Even if it's currently unmaintained, it doesn't render its functionality useless. So if there are no known security issues, I'd like to stick with it for now and maybe get back to replacing it later.
