### ISSUE TITLE
unable to build with libressl 3.4.1

### ISSUE THREAD

**Issue by tuesdaycodes** [alexliesenfeld/httpmock#52]
libressl 3.4.0 seems the latest supported but 3.4.1 is out and is in use by my platform/os. is it possible the supported version can be bumped please?

**Comment by alexliesenfeld** [comment]
Thanks for creating this issue. Version 0.6.4 bumps all dependencies to newest possible version. Therefore, this issue will be closed. Feel free to reopen it if you still have problems on your end.
