### ISSUE TITLE
Replace unmaintained difference by similar

### ISSUE THREAD

**Issue by theredfish** [alexliesenfeld/httpmock#54]
The crate `difference` is unmaintained, I originally saw this in my repository RUSTSEC issue : https://github.com/theredfish/grillon/issues/6

I propose to replace `difference` by `similar` which is part of the recommended maintained crates, and also quite popular in comparison of the others.

Please see my PR.

**Comment by alexliesenfeld** [comment]
Thanks for creating this issue and PR. I'll have a look into it soon!
