### ISSUE TITLE
GRPC support

### ISSUE THREAD

**Issue by marlon-sousa** [alexliesenfeld/httpmock#61]
Hello,

Is there a reliable way of using this to test GRPC calls?

Perhaps by providing a layer to parse a proto and translate first messages to json, use the current implementation and translate back the response?

Trying to understand if this could be realistically implemented in a easy form.

Thanks,
Marlon

**Comment by alexliesenfeld** [comment]
I would assume that this would require substantial changes to the library. However, considering that this library already tries to cover a lot of functionality, adding gRPC would yet add much more.
