### ISSUE TITLE
Add `When::query_unset` for a criterion that a query parameter is not present

### ISSUE THREAD

**Issue by ahl** [alexliesenfeld/httpmock#75]
First: love this crate. Thank you.

I have a situation where I want a server with two similar mocks: one where a particular query parameter is set; another where it is not. I can make it work by specifying the query-set mock first, but that ordering feels a little fragile. I would love it if there were a way to do something like this:

```rust
    let unset = server.mock(|when, then| {
        when.query_unset("foo");
        // ...
    });
    let set = server.mock(|when, then| {
        when.query_param("foo", "bar");
        // ...
    });
```

If you'd be amenable, I'd be happy to submit a PR for this functionality.

**Comment by ahl** [comment]
I see! So something like this:

```rust
        when.into_inner().matches(|req| {
            req.query_params
                .as_ref()
                .and_then(|qs| qs.iter().find(|(key, _)| key == "x"))
                .is_none()
        });
```

That works; thanks. Feel free to close this

**Comment by balbifm** [comment]
Hi, wasn't sure if should open another issue, but related to this exact request: Would it still make sense to add such criterion for query_params and headers given that _matches_  does not work for remote mock servers? 

Thanks in advance!
