### ISSUE TITLE
Add `Then::remove_after_n` to self-delete a mock after N hits

### ISSUE THREAD

**Issue by ahl** [alexliesenfeld/httpmock#76]
Again: love this crate.

I've found some situations where I would like a `Then` to specify a response (in my case once) and then for a subsequent call with the same parameters to get a different response. One way I could imagine doing it is like this:

```rust
    let mock1 = server.mock(|when, then| {
        when.any_request();
        then.status(200).remove_after_n(1);
    });
    let mock2 = server.mock(|when, then| {
        when.any_request();
        then.status(503);
    });
```

Happy to submit a PR if this seems reasonable. Thanks.

**Comment by alexliesenfeld** [comment]
Hi @ahl ! If a manual removal is sufficient for you, you could use `mock1.delete()`, like here: https://github.com/alexliesenfeld/httpmock/blob/d87ab088fff6c5f2e2aacf8083874f357111b1cd/tests/examples/delete_mock_tests.rs#L27

**Comment by ahl** [comment]
I noticed `Mock::delete` but the situation we're considering basically looks like this:

```rust
let mock1 = server.mock(...); // respond with transient failure
let mock2 = server.mock(...); // respond with success

operation_that_should_retry_failed_queries();
```

So we don't (I think?) have an opportunity to call `delete`.

**Comment by ahl** [comment]
@alexliesenfeld any more thoughts on this? Thanks.

**Comment by alexliesenfeld** [comment]
Sure, I'd accept a PR!

**Comment by ahl** [comment]
I'll work on a PR; assert_hits doesn't do what we have in mind here.
