### ISSUE TITLE
latest docker image failing

### ISSUE THREAD

**Issue by aaronenberg** [alexliesenfeld/httpmock#83]
Hey, thanks for this awesome tool.

I am seeing this error when running with the latest docker image:

```bash
$ httpmock --expose true
error: unexpected argument 'true' found

Usage: httpmock [OPTIONS]

For more information, try '--help'.
```

This does not happen with image tagged `alexliesenfeld/httpmock:0.6.2`

**Comment by aaronenberg** [comment]
my guess is this broke when upgrading to clap=4.0

**Comment by aaronenberg** [comment]
I would suggest updating the Dockerfile to `ENTRYPOINT ["httpmock", "--expose"]` removing the "true" part because it seems like there is some extra clap setup needed to parse values for bool arguments

**Comment by alexliesenfeld** [comment]
Thanks for reaching out. Yes, the Docker image needed an update. It was updated today with https://github.com/alexliesenfeld/httpmock/pull/86 and [`v0.6.8`](https://github.com/alexliesenfeld/httpmock/releases/tag/v0.6.8)
