### ISSUE TITLE
could not find `internal` in `regex`

### ISSUE THREAD

**Issue by JasterV** [alexliesenfeld/httpmock#87]
![image](https://github.com/alexliesenfeld/httpmock/assets/49537445/585ce83d-f666-4c76-9429-9e55454b5d45)

I don't know what is going on please help

**Comment by alexliesenfeld** [comment]
This should have been fixed in https://github.com/alexliesenfeld/httpmock/issues/84 with v0.6.8.

**Comment by JasterV** [comment]
@alexliesenfeld You are completely right, upgrading the version solved the problem

Thank you!
