### ISSUE TITLE
Question about type correctness and the http crate

### ISSUE THREAD

**Issue by Ducky2048** [alexliesenfeld/httpmock#89]
I just started using httpmock. One thing I immediately noticed is how it doesn't seem to be using the types I'd consider most appropriate.

The `http` crate defines commonly needed http related types which are used by a lot of well-known libraries in the ecosystem like [tower, hyper and reqwest](https://crates.io/crates/http/reverse_dependencies). 

To my surprise, this crate doesn't. For example, it redefines the http `Method` enum instead of using the types from the `http` crate "everyone else" in the ecosystem uses. I think it would be better to use the common types.

Something else I noticed: `When.header` taking `(Into<String>, Into<String>)`  instead of the (in my opinion) properly typed `(Into<http::HeaderName>, Into<http::HeaderValue>)`. (Not every String is a valid http header, which is why in my opinion this type is not quite correct.)

Also, `when.Body` takes an `Into<String>`, but http can transport many things in its body, including binary data. This is accounted for in `Then` as it takes an `impl AsRef<[u8]>` but not in `When`, preventing (as far as I can tell) matching on non-string request bodies.

Are these intentional design choices? If not, would you consider pull requests adressing this?

**Comment by alexliesenfeld** [comment]
As far as I see it, the `http` crate is not really designed for ease of use but correctness. The data structures `httpmock` uses are designed to easily access data. Some `httpmock` data structures, such as `HttpMockRequest`, allow you to "unwrap" or convert to some of these structures (including `http` crates data structures).
