### ISSUE TITLE
Update to hyper >=1.0

### ISSUE THREAD

**Issue by gtema** [alexliesenfeld/httpmock#97]
It would be great if dependency on hyper can be updated (to >= 1.0, ideally 1.1). This causes quite a big set of dependencies in my project stuck with older versions.

**Comment by alexliesenfeld** [comment]
Thanks for creating this issue. I'm, working on it in https://github.com/alexliesenfeld/httpmock/tree/upgrade-hyper .

**Comment by jayvdb** [comment]
For some reason, https://github.com/alexliesenfeld/httpmock/pull/98 was not merged.

**Comment by alexliesenfeld** [comment]
@alexliesenfeld I have migrated it in a private development branch. httpmock 0.8 will bring significant improvements but it still takes a bit time to get everything stable. So it’s done bot not shipped yet.

**Comment by jayvdb** [comment]
It has been 7 months since the last release.  When are you expecting to be able to release 0.8?

Maybe #98 could be merged and released as 0.7.1  which is mentioned as the next release in the CHANGELOG.md ?

**Comment by alexliesenfeld** [comment]
> When are you expecting to be able to release 0.8?

I expect the first alpha to be shipped in a few weeks. 

> Maybe https://github.com/alexliesenfeld/httpmock/pull/98 could be merged and released as 0.7.1 which is mentioned as the next release in the CHANGELOG.md ?

Releasing it in 0.7.1 would more or less require me to do the work twice, because `httpmock` was entirely rewritten for 0.8.0. I'm trying to put my available time 100% into shipping it. I hope you understand.

**Comment by jayvdb** [comment]
ok, looking forward to the alpha!

**Comment by jayvdb** [comment]
to clarify, https://crates.io/crates/httpmock/0.8.0-alpha.1 has been released.  Thanks.  Trying it out
